### ISSUE TITLE
[Bug] Can't compile

### ISSUE THREAD

**Issue by vithushan19** [creativetimofficial/nextjs-material-kit#1]
### Version
1.0.0
### Operating System
Mac OS
### Device
Macbook Pro
### Browser & Version
Chrome V76
### Steps to reproduce
copy the next.config.js file from the example
next build
### What is expected?
successful compile
### What is actually happening?
Creating an optimized production build

> 
> Failed to compile.
> 
> ./node_modules/next-material-kit/components/Grid/GridContainer.js 23:4
> Module parse failed: Unexpected token (23:4)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |   const { children, className, ...rest } = props;
> |   return (
> \>     <Grid container {...rest} className={classes.grid + " " + className}>
> |       {children}
> |     </Grid>
> 
> \> Build error occurred
> Error: \> Build failed because of webpack errors
>     at build 
> 

---

**Comment by EINazare** [comment]
Hello there, @vithushan19 ,

I will require from you some additional comments.
Such as:
You say in your comment this:
```
copy the next.config.js file from the example
next build
```
You've copied our next.config.js where?
Why did you do that?
What are you trying to accomplish by doing this?

If I download this project, run `npm install` then `npm run build` then `npm start`, everything works as expected.
Here is the list of the command that you can use with this project: https://demos.creative-tim.com/nextjs-material-kit/documentation/buildtools

Best,
Manu
