### ISSUE TITLE
[Bug] npm registry name wrong

### ISSUE THREAD

**Issue by Memo99** [creativetimofficial/nextjs-material-kit#17]
### Version
latest
### Reproduction link
https://github.com/creativetimofficial/nextjs-material-kit/blob/master/README.md
### Operating System
Windows
### Device
wayne
### Browser & Version
wayne
### Steps to reproduce
npm i nextjs-material-kit
### What is expected?
download the package
### What is actually happening?
error

---
### Solution
npm i next-material-kit

**Comment by EINazare** [comment]
Hello there, @Memo99 ,

Thank for your issue.
Until we solve this, please download the product and use it like so.
Also, you could check this thread here: creativetimofficial/ct-material-dashboard-pro-react#50 (comment)

Best,
Manu
