### ISSUE TITLE
[Feature Request] Upgrade to latest NextJS v9.3.0

### ISSUE THREAD

**Issue by kydreth** [creativetimofficial/nextjs-material-kit#2]
### What is your enhancement?
update package.json to include NextJS v9.3.0

**Comment by kydreth** [comment]
@EINazare can you approve and merge this please? Thanks

**Comment by EINazare** [comment]
Hello there, @kydreth ,

I'll try to update this product ASAP.

Best,
Manu

**Comment by kydreth** [comment]
Thanks @EINazare it was already merged into dev master branch. This can be closed when merged into the default branch / master. Thanks

**Comment by kydreth** [comment]
@EINazare is branch dev-master going to be merged into master?

**Comment by EINazare** [comment]
Hello there, @kydreth ,

Yes, in our next update.
![Screen Shot 2020-04-21 at 12 29 07 PM](https://user-images.githubusercontent.com/26245512/79849863-b9fa2680-83cb-11ea-98be-6751959616c6.png)

Best,
Manu
