### ISSUE TITLE
[Bug] Unable to install dependencies

### ISSUE THREAD

**Issue by salvobee** [creativetimofficial/nextjs-material-kit#20]
### Version
1.2.0
### Reproduction link
https://www.creative-tim.com
### Operating System
Ubuntu 20.04 (WSL)
### Device
Desktop
### Browser & Version
npm 7.11.1
### Steps to reproduce
Download the .zip package from Creative Tim website
Unzip the package
run `npm install` or `npm install:clean`
### What is expected?
Install npm dependencies
### What is actually happening?
npm is unable to resolve dependency tree:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: next-material-kit@1.2.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0" from react-datetime@3.0.4
npm ERR! node_modules/react-datetime
npm ERR!   react-datetime@"3.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

---
### Solution
I've used yarn to install dependencies (which shows the above described error as a simple warning), probably the issue could be fixed using `--force` with npm

**Comment by sajadevo** [comment]
Hi there, 

We've updated the products and this issue is fixed now please update to the latest version of the product (v1.2.1).

Regards,
Sajad
