### ISSUE TITLE
[Bug] npm i Failed

### ISSUE THREAD

**Issue by iamthehimansh** [creativetimofficial/nextjs-material-kit#24]
### Version
1.2.0
### Reproduction link
https://github.com/creativetimofficial/nextjs-material-kit
### Operating System
Windoes
### Device
Windoes
### Browser & Version
Chrome
### Steps to reproduce
npm i
### What is expected?
to install Properly 
### What is actually happening?
not installing

---
### Additional comments
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\iamth\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js

PATH: 
  C:\Python\Python310\Scripts\;C:\Python\Python310\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\Program Files\PuTTY\;C:\Python\python376\Scripts\;C:\Python\python376;C:\Python\Python310\Scripts;C:\Python\Python310;C:\Users\iamth\AppData\Local\Microsoft\WindowsApps;C:\Users\iamth\AppData\Roaming\npm;C:\Users\iamth\AppData\Local\Programs\Microsoft VS Code\bin;C:\Bin;C:\Program Files\heroku\bin;

Yarn version: 
  1.22.17

Node version: 
  16.11.1

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.11.2.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (C:\Users\iamth\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141510:19)
      at Object.onceWrapper (node:events:509:28)
      at ClientRequest.emit (node:events:390:28)
      at TLSSocket.emitRequestTimeout (node:_http_client:763:9)
      at Object.onceWrapper (node:events:509:28)
      at TLSSocket.emit (node:events:402:35)
      at TLSSocket.Socket._onTimeout (node:net:486:8)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

npm manifest: 
  {
    "name": "next-material-kit",
    "version": "1.2.0",
    "description": "NextJS Version of Material Kit React by Creative Tim (https://creative-tim.com)",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1",
      "dev": "next",
      "build": "next build",
      "start": "next start",
      "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && rm -rf .next/ && npm install && npm run dev"
    },
    "repository": {
      "type": "git",
      "url": "git+https://github.com/creativetimofficial/nextjs-material-kit.git"
    },
    "keywords": [
      "next",
      "nextjs",
      "react",
      "reactjs",
      "npx",
      "material",
      "material-design",
      "material-kit",
      "material-kit-react",
      "next-material-kit"
    ],
    "author": "Creative Tim",
    "license": "MIT",
    "bugs": {
      "url": "https://github.com/creativetimofficial/nextjs-material-kit/issues"
    },
    "homepage": "https://demos.creative-tim.com/nextjs-material-kit",
    "dependencies": {
      "@material-ui/core": "4.11.4",
      "@material-ui/icons": "4.11.2",
      "classnames": "2.3.1",
      "moment": "2.29.1",
      "next": "10.2.0",
      "next-compose-plugins": "2.2.1",
      "next-images": "1.7.0",
      "nextjs-redirect": "5.0.2",
      "node-sass": "5.0.0",
      "nouislider": "15.1.0",
      "path": "0.12.7",
      "prop-types": "15.7.2",
      "react": "17.0.2",
      "react-datetime": "3.0.4",
      "react-dom": "17.0.2",
      "react

**Comment by sajadevo** [comment]
Hi there, 

We've updated the products and this issue is fixed now please update to the latest version of the product (v1.2.1).

Regards,
Sajad
