### ISSUE TITLE
[Bug] Installing using `npm i` fails due to React/MUI mismatch

### ISSUE THREAD

**Issue by nk9** [creativetimofficial/nextjs-material-kit#30]
### Version
1.2.1
### Reproduction link
https://github.com/creativetimofficial/nextjs-material-kit
### Operating System
macOS 12.6.2
### Device
N/A
### Browser & Version
N/A
### Steps to reproduce
1. Download source
2. Run `npm i` as directed in setup instructions
### What is expected?
I'd expect npm to install all the dependencies
### What is actually happening?
Error:

```
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: v7-website@1.2.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.11.4
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"4.11.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/nick/.npm/_logs/2023-02-15T16_44_47_907Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nick/.npm/_logs/2023-02-15T16_44_47_907Z-debug-0.log
```

---
### Solution
I think one solution is to use React 16, which is compatible with MUI 4, at least according to the error above. Not ideal. I don't really know how else to fix this. TBH, this sort of integration issue was one of the main reasons I was hoping to use a template like this…

### Additional comments
I'm using NodeJS 18.14

**Comment by sajadevo** [comment]
Hey there,

Just use the following command: `npm i --legacy-peer-deps`

Regards,
Sajad

**Comment by nk9** [comment]
Thanks for the quick comment, but if the instructions don't work, then I still think this is a bug. Maybe it's a documentation bug?
