### ISSUE TITLE
[Bug] .MuiCheckbox-colorSecondary.Mui-checked:hover effect needs to be overwritten on checkbox/radio

### ISSUE THREAD

**Issue by kydreth** [creativetimofficial/nextjs-material-kit#5]
### Version
1.0.0
### Reproduction link
https://github.com/creativetimofficial/nextjs-material-kit
### Operating System
Windows 10
### Device
Laptop
### Browser & Version
Chrome 80.0.3987.132
### Steps to reproduce
1. git clone https://github.com/creativetimofficial/nextjs-material-kit.git
2. npm install
3. npm run dev
### What is expected?
Hover mouse over checkbox, radio and you'll see the .MuiCheckbox-colorSecondary.Mui-checked:hover effect *is using a color defined this defined theme*
### What is actually happening?
Hover mouse over checkbox, radio and you'll see the .MuiCheckbox-colorSecondary.Mui-checked:hover effect is using a color outside this defined theme

---

**Comment by kydreth** [comment]
@EINazare are you able to work on this one?

**Comment by EINazare** [comment]
Hello there, @kydreth ,

Thank you for your interest in working with our products.
Go inside `assets/jss/nextjs-material-kit/customCheckboxRadioSwitch.js` and change lines
```
  checkRoot: {
    padding: "12px",
    "&:hover": {
      backgroundColor: "unset"
    }
  },
  radioRoot: {
    padding: "12px",
    "&:hover": {
      backgroundColor: "unset"
    }
  },
```
To:
```
  checkRoot: {
    padding: "12px",
    "&:hover": {
      backgroundColor: "unset!important"
    }
  },
  radioRoot: {
    padding: "12px",
    "&:hover": {
      backgroundColor: "unset!important"
    }
  },
```

The link you have provided sends me to this repository, next time it would be more helpful if you would give us a link that will send us to the page with the issue.

Best,
Manu

**Comment by kydreth** [comment]
@EINazare understood! It was the components page. Any of the radio, checkbox, switch components. The above works for disabling the radio and checkbox hover box shadow, not providing the theme color. I can take a shot at this over the weekend maybe? If it's not a quick fix.
