### ISSUE TITLE
[Bug] hardcoded values of theme colors in assets/jss

### ISSUE THREAD

**Issue by kydreth** [creativetimofficial/nextjs-material-kit#6]
### Version
1.0.0
### Reproduction link
https://github.com/creativetimofficial/nextjs-material-kit
### Operating System
Windows 10
### Device
Laptop
### Browser & Version
Chrome 80.0.3987.132
### Steps to reproduce
1. git clone https://github.com/creativetimofficial/nextjs-material-kit.git
2. npm install
3. npm run dev
4. change color such as primaryColor in assets/jss/nextjs-material-kit.js
### What is expected?
All primaryColor's change for all components
### What is actually happening?
Several components have hardcoded values for theme colors

---
### Solution
Remove hardcoded values in jss/ directory and reference the variables 
### Additional comments
I'll try to put a commit against this today

**Comment by EINazare** [comment]
Hello again, @kydreth ,

Can you please give us the hardcoded values?
I've checked and it seems that all jss components make use of the variables from the `assets/jss/nextjs-material-kit.js` file.

Best,
Manu

**Comment by kydreth** [comment]
I updated them with variables and committed. They're already merged. This should be closed when merged into the default branch / master
